### ISSUE TITLE
[GPP/Cronus/Titan] Problem with two GIMX instances

### ISSUE THREAD

**Issue by MrAngry777** [matlo/GIMX#305]
Its nearly impossible to start more than one GIMX instance. Because the GPP config does not let you choose port or device and when using two DIY configuration they both use the same controller which makes in turn multiplayer configuration impossible plus after some time one instances stops to send input. Would it be possible to add the controller choice box to GIMX?

**Comment by matlo** [comment]
Fixed in both Linux and Windows.
