### ISSUE TITLE
Keyboard emulation

### ISSUE THREAD

**Issue by MrAngry777** [matlo/GIMX#306]
It would be great if you had to gimx modes and you could switch from Pad mode to Keyboard mode. So when you play and a chat pops up you press a button write your response and then back into the game.

**Comment by matlo** [comment]
It could be done, but it requires to have an additional DIY USB adapter that emulates a keyboard.

**Comment by MrAngry777** [comment]
The DIY is so cheap that I would love to see that kind of functionality. Could I ask you to include this feature in the next release?

**Comment by matlo** [comment]
This is not an easy one, and there already are lots of features planned for the next release...
