### ISSUE TITLE
[DIY USB adapter, PS4, Linux] GIMX fails to initialize the DS4 controller

### ISSUE THREAD

**Issue by F0xHunt3r** [matlo/GIMX#321]
After updating to GIMX 4.0 I get the following error.  I already updated the teensy to 4.0 as well.

libusb_set_configuration:  Resource busy
No Controller was found on USB buses.
connector_init failed
![image](https://cloud.githubusercontent.com/assets/8643388/7677687/70bcb736-fd0b-11e4-9c88-400812c54dd7.png)

If I boot into Windows and use version 3.5 it works

**Comment by matlo** [comment]
Thanks for reporting.
