### ISSUE TITLE
[Windows] Libusb-usbdk error after installing usbdk twice

### ISSUE THREAD

**Issue by matlo** [matlo/GIMX#324]
As a work-around, uninstall and reinstall usbdk.

**Comment by matlo** [comment]
The installer will uninstall and reinstall usbdk until the usbdk installation gets fixed.

**Comment by matlo** [comment]
Uninstalling and reinstalling usbdk may cause bsods... so this is not a good work around.

**Comment by matlo** [comment]
https://github.com/daynix/UsbDk/issues/1

**Comment by jpenalbae** [comment]
After installing GIMX in Win7 x64 the system won't boot any more. I had to restore the system from a previous restore point.

This happened me twice, so I suspect it's related to gimx and probably to Libusb-usbdk.
