### ISSUE TITLE
adapter_network_read: wrong packet size

### ISSUE THREAD

**Issue by Serphentas** [matlo/GIMX#333]
Hi,

I can't seem to get this working. I upgraded from 3.x (can't remember exact version) to 4.2 and now I can't use remote GIMX.

Setup:
from Win7 x64 to RPi (Raspbian) controlling PS3 via BT

**Comment by Serphentas** [comment]
Might as well add the error I get whenever I start the remote client on Win7:
adapter_network_read: wrong packet size
This message is spammed a lot and nothing happens on the ps3.

**Comment by matlo** [comment]
Hi,
Do the client and server software version match?

**Comment by Serphentas** [comment]
Normally, yes. I've run apt-get update/upgrade on the linux target.

**Comment by matlo** [comment]
You have to upgrade gimx manually:
```
wget https://github.com/matlo/GIMX/releases/download/v4.2/gimx_4.2-1_armhf.deb
sudo dpkg -i gimx_4.2-1_armhf.deb
```

**Comment by Serphentas** [comment]
Indeed, that was it. Connection can now be established, thank you.
