### ISSUE TITLE
[Xbox One] Support for newer controllers

### ISSUE THREAD

**Issue by matlo** [matlo/GIMX#336]
This controller has different USB ids: 045E:02DD.

**Comment by OmniPlatGames** [comment]
What is the status on this? Has anyone started looking into it? I'm guessing these controllers are the new ones with the Audio jack, considering this is the issue I am having.

**Comment by matlo** [comment]
I have protocol captures and a wired 3.5mm controller, but I'm currently lacking time to work on it.

**Comment by Cjkeenan** [comment]
I have another controller with the USB ids - 24C6:543A which does not work as well, it just when I click start, it resets the adapter then it says it cannot find it. It is a third party one I got from Gamestop but it works fine with the Xbox One though.

**Comment by GodlikeRU** [comment]
Any progress on this? I was thinking about buying new Xbox One S controller to replace this DS4 shit on my PS4 but it seems it won't work without gimx update.

**Comment by matlo** [comment]
Fixed by #619. Controllers with VID/PID 045e:02dd (2015 update) and 045e:02ea (xbox one s update) are now supported.
