### ISSUE TITLE
GIMX i386 does not work on 64bit Windows

### ISSUE THREAD

**Issue by matlo** [matlo/GIMX#343]

**Comment by the4anoni** [comment]
There are this same issue #327

**Comment by matlo** [comment]
Installing GIMX i386 on a 64-bit Windows will be forbidden until USBDK provides a 32-bit usbdkHelper.dll in the x64 installer.

**Comment by matlo** [comment]
The updater should also download the right GIMX installer.

**Comment by matlo** [comment]
USBDK 1.0.7 provides the 32-bit usbdkHelper.dll in the x64 installer.
Upgrading to USBDK 1.0.7 will fix the issue.
