### ISSUE TITLE
Logitech FFB improvements

### ISSUE THREAD

**Issue by matlo** [matlo/GIMX#350]
Forward more commands like default spring on / off, store download force, and convert play force into download and play force. Filter play/stop/download and play commands depending on the current state. Always send a command when all forces are stopped together.

**Comment by Alexanderlee1993** [comment]
![2B140EF5-0D48-419D-92D6-49A3CD684E2F](https://user-images.githubusercontent.com/87406551/125559812-602ef34f-f823-42e7-85a9-221231af6c7d.png) please! Tell me how to do please!
