### ISSUE TITLE
GIMX does not work with at90usb162, at90usb1286 and at90usb1287 boards.

### ISSUE THREAD

**Issue by matlo** [matlo/GIMX#367]
Reported here: http://gimx.fr/forum/viewtopic.php?f=5&t=1443

**Comment by matlo** [comment]
Reported here: https://forum.gimx.fr/viewtopic.php?f=5&t=1517&start=20

**Comment by matlo** [comment]
Reported here: http://gimx.fr/forum/viewtopic.php?p=9020#p9020

**Comment by p-baxter** [comment]
Any updates on this? Do you happen to know what the issue is?

**Comment by matlo** [comment]
Sadly I did not have enough time to work on this.

**Comment by matlo** [comment]
Closing due to lack of time / interest.
