### ISSUE TITLE
Command line arguments now require specific ordering

### ISSUE THREAD

**Issue by imbrianj** [matlo/GIMX#374]
This came as a bit of a surprise.  I had been using Gimx for years, but after an upgrade to 5.6 ARMv6 (from 4.3), it now requires specific ordering of command arguments.

To test, I was running:

```
pi@switchboard ~ $ gimx --dst 127.0.0.1:8181 --event "right(255)"
option -d with value `127.0.0.1:8181'
option -e with value `right(255)'
Detected controller: Sixaxis.
using default refresh period: 10.00ms
The --event argument may require running two gimx instances.
```

However, when I changed the order of the arguments, it appears to work:

```
pi@switchboard ~ $ gimx --event "right(255)" --dst 127.0.0.1:8181
option -e with value `right(255)'
option -d with value `127.0.0.1:8181'
Detected controller: Sixaxis.
using default refresh period: 10.00ms
```

Expected behavior: That gimx would execute regardless of argument order.

**Comment by matlo** [comment]
Hi Brian,
Sorry about this change, but it is required for emulating multiple controllers.
I'll improve the documentation and I'll update the command output to indicate which argument is used for which controller, and I'll close this issue.

**Comment by imbrianj** [comment]
Ahh, makes sense.  Thanks for the clarification.  I had assumed it was a bug.

**Comment by matlo** [comment]
I'll keep the issue opened until I fix the command output.
