### ISSUE TITLE
Sensitivity adjustment ranges from 0.004 to 0.008 instead of -100 to 100

### ISSUE THREAD

**Issue by Mat768** [matlo/GIMX#375]
Hi,
I have noticed that the axis sensitivity adjustment value can only be set between 0.004 and 0.008. Otherwise, when i start a game, the axis simply does not work. It works fine if adjusted between these 2 values, but this gives very little room for adjustment, since the resolution of this entry seems to be limited to 3 decimals.
When overing this field with the mouse, it says that the value should be set between [-100.00..100.00], which does not work at all. Is this normal?

**Comment by matlo** [comment]
I don't think there's a resolution limit.
For example a value like 0.00039 should work fine.
