### ISSUE TITLE
More flexibility in axis configuration needed

### ISSUE THREAD

**Issue by Mat768** [matlo/GIMX#376]
I am wondering if it could be possible to have greater flexibility to configure the "shape" of an axis. For instance, i have tried to use a g25 to drive in GTA5 on PS4. I managed to make it work, but since the game itself is configured to be using a controller joystick, the shape of the axis is fairly non-linear. This means that the minimal default deadzone is fairly large (even if set to 0 in gimx + logitech profiler). Also, the first degres of rotation, close to the middle have little effect, then, the more you turn the wheel (or push the joystick), the more effect it has. There seems to be an acceleration programmed in the game itself. Since nothing can be changed in the game itself to make it more linear, i think it would be nice to have the flexibility to modify the shape of the axis. For instance, movement of the wheel (or joystick) could be set to have more effect when close to the middle, and less effect when reaching the travel limits, this would allow to compensate for the game motion control and make a non linear axis more linear (think of it as an adjustable logarithmic multiplier). This could also be useful in other instances, for example, if you wanted to make an actual linear control have a certain accelleration factor. It would also be nice if the range of linearity vs non linearity could be configured...I am no programmer but i think this could be done, and even if fairly complicated to set, it would offer great flexibility!! (restore to default button would be an abolute necessity :-P ). Thanks

**Comment by matlo** [comment]
The acceleration parameter allows to modify the overall acceleration.
The sensitivity parameter has to be changed accordingly.
The acceleration parameter is currently caped into [0 ..2], I will increase the upper limit to allow more flexibility.
