### ISSUE TITLE
Segfault after pairing

### ISSUE THREAD

**Issue by PixelToast** [matlo/GIMX#377]
After the "Did you saved your dongle address" dialog a few seconds later i get a segmentation fault
Backtrace: http://hastebin.com/raw/ruwasuqiyi

Installed from latest release, gimx_5.7-1_amd64.deb

I can compile with debug symbols if needed

EDIT:

I am using cinnamon and i had to enable Bluetooth with its builtin blueman-applet
some error checking where it segfaulted would have been nice! (im willing to PR it on my own if nobody fixes it in a few days)

**Comment by matlo** [comment]
Which GNU/Linux distro are you using?

**Comment by PixelToast** [comment]
up to date debian jessie on a laptop, USB dongle is ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode)

**Comment by matlo** [comment]
If you can fix it please do it. I'm currently very busy.

**Comment by matlo** [comment]
The .deb was built for Ubuntu 14.04. I guess there's a compatibility issue with Debian Jessie.
Feel free to investigate and reopen the issue if it's not a compatibility issue.
