### ISSUE TITLE
Fatal Error: Mismatch between the program and library build versions detected.

### ISSUE THREAD

**Issue by andreaslyngstad** [matlo/GIMX#388]
Hi

I am on ubuntu 15.10

When I try to start gimx-launcher from the launcher nothing happens 

When I start gimx-launcher in the terminal I am getting 
`Fatal Error: Mismatch between the program and library build versions detected.
The library used 2.8 (no debug,Unicode,compiler with C++ ABI 1009,wx containers,compatible with 2.6),
and your program used 2.8 (no debug,Unicode,compiler with C++ ABI 1002,wx containers,compatible with 2.6).
Aborted (core dumped)
`
I dont know if this is a bug with gimx or if there is a error on my computer. 

I have tried different versions of gimx. Down to 4.3-1

**Comment by matlo** [comment]
As per the wiki page only Ubuntu 14.04 is supported.
Ubuntu 16.04 will be the next supported version.

**Comment by andreaslyngstad** [comment]
Ok. Thanks for this project and your quick response!
