### ISSUE TITLE
Repair DS4

### ISSUE THREAD

**Issue by Cybereu** [matlo/GIMX#391]
Option to repair ds4 to gimx should be on Interface, since we talked on:

http://gimx.fr/forum/viewtopic.php?f=5&t=1561&sid=caff363328503f0bd50b5938b112e2b5

**Comment by matlo** [comment]
I'm thinking about changing the name of the "New" button to "New/Repair".
When clicking on this button, if a known DS4 has a wrong master, the user will be requested if it should be fixed. In other cases, the classic pairing procedure will be started.
