### ISSUE TITLE
[Windows] Wheel gets randomly stuck

### ISSUE THREAD

**Issue by AMS97F1** [matlo/GIMX#393]
Hi, So I've been playing F1 2016 with the GIMX adapter and a DFGT the last couple of days, and it has largely been fine. 

But every now and again, the wheel just disconnects - and whatever I was doing at the time, the wheel continues to do. For example, I was braking into a corner, and as I was braking it happened, and my car came to a complete halt and then reversed backwards until it reconnected. 

I can generate a log file later on tonight if you want that, but if you know how to solve the issue before then, that would be great!

**Comment by matlo** [comment]
Sadly there are various causes for connection issues.
A log file generated while the issue happens is required.

**Comment by matlo** [comment]
You should also keep posting in the support section of the forum.
It's still unclear if this is a real issue or not.

**Comment by AMS97F1** [comment]
Ok sure thing, once I've got the log file with the issue, I'll post both here and there if you like.

**Comment by AMS97F1** [comment]
Ok so here is the log file. It's rather long...

[log2.txt](https://github.com/matlo/GIMX/files/430885/log2.txt)

**Comment by matlo** [comment]
A similar issue has been reported here:
http://gimx.fr/forum/viewtopic.php?f=5&t=1754

**Comment by AMS97F1** [comment]
Ok thanks, I'll try out Linux on a partition too and I'll report back.

**Comment by AMS97F1** [comment]
Ok, so I decided to give my wheel one more chance before the partition, and since I disabled windows updates, it has been ok. I've played at least 3-4 hours with no issues. So that seems to have been the problem, but I can't be 100% sure for at least another couple of days.

**Comment by AMS97F1** [comment]
So after disabling Windows updates it seemed fine for a couple of days, but it happened last night and then I set my PC to not sleep, it still did it tonight. Last night it was two very short disconnects, maybe 3 or 4 seconds. Tonight it happened a couple of times, each around 20 - 30 seconds. 

Really have no idea what else I can do at this point short of changing cables...Do you have any recommendations of what to do (Besides a partition), matlo?

**Comment by matlo** [comment]
Try in Linux Mint 17.3!

**Comment by AMS97F1** [comment]
Ok so I actually tried using my windows 10 laptop (Disconnected from WiFi) and I've not had an issue the past two days. Think ive solved that problem tbh.

Really though, it needs to be identified why it doesnt work, because not everyone has 2 computers with different two different operating systems to try. Installing Linux isn't really a proper solution. I was hoping I'd find the solution so that others don't have to get frustrated with it.

**Comment by matlo** [comment]
I wasn't suggesting you to install Linux Mint.
It's easy to install and run GIMX in a live usb session, and it can help understanding the issue.

The issue seems to be related to Windows 7.
As I'm running out of free time I'll release GIMX 6.0 first and if the problem remains, then I'll investigate.

**Comment by matlo** [comment]
GIMX 6.0 is out. Please let me know if the issue still happens.
