### ISSUE TITLE
Custom deadzone shapes.

### ISSUE THREAD

**Issue by Cybereu** [matlo/GIMX#395]
At the moment there are 2 deadzone shapes, they cover almost every game but there are a lot AAA games that dont use square or elipse shape as showed here: 
https://drive.google.com/drive/mobile/folders/0B3jq3Adc2gXiRExmcncyQ0ZUYXEtOGNwTmxJcm9yUQ

Improvement: Custom shape on given formula by user.

**Comment by matlo** [comment]
This is similar to #143.

I think the dead zone calibration mode could be improved to produce the exact dead zone shape.
And the exact dead zone shape could be embedded into the configuration file.

**Comment by matlo** [comment]
Duplicate of #143.
