### ISSUE TITLE
Fresh Linux install. Building source gives errors.

### ISSUE THREAD

**Issue by MegaJiXiang** [matlo/GIMX#396]
I followed the exact instructions on the website for my distro and get errors when building.

Here is my log output:
make -j 4
make -C utils
make -C shared
make -C po
make[1]: Entering directory '/home/jodymcadams/Documents/GIMX/po'
make[1]: 'all' is up to date.
make[1]: Leaving directory '/home/jodymcadams/Documents/GIMX/po'
make[1]: Entering directory '/home/jodymcadams/Documents/GIMX/shared'
make -C controller
make -C event
make -C updater
make[1]: Entering directory '/home/jodymcadams/Documents/GIMX/utils'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/jodymcadams/Documents/GIMX/utils'
make -C configupdater
make[2]: Entering directory '/home/jodymcadams/Documents/GIMX/shared/controller'
make[2]: Entering directory '/home/jodymcadams/Documents/GIMX/shared/updater'
make[2]: Entering directory '/home/jodymcadams/Documents/GIMX/shared/configupdater'
make[2]: Entering directory '/home/jodymcadams/Documents/GIMX/shared/event'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/jodymcadams/Documents/GIMX/shared/event'
make -C async
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/jodymcadams/Documents/GIMX/shared/updater'
make -C gpp
make[2]: Entering directory '/home/jodymcadams/Documents/GIMX/shared/async'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/jodymcadams/Documents/GIMX/shared/configupdater'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/jodymcadams/Documents/GIMX/shared/controller'
make -C configeditor
make[2]: Entering directory '/home/jodymcadams/Documents/GIMX/shared/gpp'
make[2]: Entering directory '/home/jodymcadams/Documents/GIMX/shared/configeditor'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/jodymcadams/Documents/GIMX/shared/async'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/jodymcadams/Documents/GIMX/shared/gpp'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/jodymcadams/Documents/GIMX/shared/configeditor'
make[1]: Leaving directory '/home/jodymcadams/Documents/GIMX/shared'
make -C core
make -C config
make -C launcher
make -C fpsconfig
make[1]: Entering directory '/home/jodymcadams/Documents/GIMX/config'
make[1]: Entering directory '/home/jodymcadams/Documents/GIMX/fpsconfig'
make[1]: Entering directory '/home/jodymcadams/Documents/GIMX/launcher'
g++ -Wall -Wextra -Wno-unused-parameter -s -O3 -I../shared/configeditor/include -I../shared/controller/include -Wno-unused-local-typedefs `wx-config --cflags` -Winvalid-pch -include wx_pch.h -DWX_PRECOMP `curl-config --cflags`  -c -o configApp.o configApp.cpp
make[1]: Entering directory '/home/jodymcadams/Documents/GIMX/core'
cc  -I/include -Wall -Wextra -Wno-unused-parameter -s -O3 -Iinclude -I../shared/event/include -I../shared/controller/include -I../shared/async/include -I../shared/gpp -I/usr/include/libxml2 -Iconnectors/btstack/include -Iconnectors/btstack/src  -c -o connectors/linux/bluetooth/bt_mgmt.o connectors/linux/bluetooth/bt_mgmt.c
g++ -Wall -Wextra -Wno-unused-parameter -s -O3 -I../shared/configeditor/include -I../shared/controller/include -Wno-unused-local-typedefs `wx-config --cflags` -Winvalid-pch -include wx_pch.h -DWX_PRECOMP `curl-config --cflags`  -c -o fpsconfigApp.o fpsconfigApp.cpp
cc   gimx-launcher.o launcherApp.o  ../shared/configeditor/configeditor.a ../shared/event/GE.a -Wl,--whole-archive ../shared/controller/controller.a ../shared/async/async.a -Wl,--no-whole-archive ../shared/gpp/gpp.a -lXi -lX11 -lusb-1.0 ../shared/updater/updater.a ../shared/configupdater/configupdater.a `wx-config --libs` `curl-config --libs` -lxml2 -lstdc++ -lm -o gimx-launcher
connectors/linux/bluetooth/bt_mgmt.c:17:28: fatal error: bluetooth/mgmt.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'connectors/linux/bluetooth/bt_mgmt.o' failed
make[1]: *** [connectors/linux/bluetooth/bt_mgmt.o] Error 1
make[1]: Leaving directory '/home/jodymcadams/Documents/GIMX/core'
Makefile:15: recipe for target 'build-core' failed
make: *** [build-core] Error 2
make: *** Waiting for unfinished jobs....
../shared/event/GE.a(GE.o): In function `GE_TimerClose':
GE.c:(.text+0x867): undefined reference to `timer_get'
../shared/event/GE.a(js.o): In function `js_process_events':
js.c:(.text+0xff): undefined reference to `timer_get'
../shared/event/GE.a(mkb.o): In function `mkb_process_events':
mkb.c:(.text+0x30e): undefined reference to `timer_get'
collect2: error: ld returned 1 exit status
<builtin>: recipe for target 'gimx-launcher' failed
make[1]: *** [gimx-launcher] Error 1
make[1]: Leaving directory '/home/jodymcadams/Documents/GIMX/launcher'
Makefile:15: recipe for target 'build-launcher' failed
make: *** [build-launcher] Error 2
In file included from fpsconfigApp.cpp:7:0:
fpsconfigApp.h:29:1: error: cannot convert ‘const wchar_t*’ to ‘const char*’ in initialization
 };
 ^
In file included from configApp.cpp:7:0:
configApp.h:30:1: error: cannot convert ‘const wchar_t*’ to ‘const char*’ in initialization
 };
 ^
<builtin>: recipe for target 'fpsconfigApp.o' failed
make[1]: *** [fpsconfigApp.o] Error 1
make[1]: Leaving directory '/home/jodymcadams/Documents/GIMX/fpsconfig'
Makefile:15: recipe for target 'build-fpsconfig' failed
make: *** [build-fpsconfig] Error 2
<builtin>: recipe for target 'configApp.o' failed
make[1]: *** [configApp.o] Error 1
make[1]: Leaving directory '/home/jodymcadams/Documents/GIMX/config'
Makefile:15: recipe for target 'build-config' failed
make: *** [build-config] Error 2

**Comment by matlo** [comment]
Hi, you may want to try the refactoring branch instead of the master branch.
It's not guaranteed to be stable and there probably are more bugs, but it may be worth to try.
