### ISSUE TITLE
gimx.fr website unreachable?

### ISSUE THREAD

**Issue by DTV96Calibre** [matlo/GIMX#400]
I'm unable to access the gimx website.
On Google Chrome and Edge any connection attempt times out as below
"This site can’t be reached
gimx.fr took too long to respond.
Search Google for gimx fr source
ERR_CONNECTION_TIMED_OUT
"
I've tried on a few different computers around my university. I seem to be able to access the site using TOR. My university uses OpenDNS if that helps, though whenever something is blocked for security reasons, I get a page telling me that's what's going on.

**Comment by DTV96Calibre** [comment]
I don't know if it's appropriate to post an issue about the website instead of the actual project here, but I didn't know how else to let somebody know it was a problem.

**Comment by matlo** [comment]
It works fine for me. Do you still get the error?

**Comment by DTV96Calibre** [comment]
Yeah, I tried it just now and I'm still unable to connect without using
TOR. I actually was able to connect by switching to my university's guest
network, so I think I'll just report this to the network admins and see if
they can fix it.
