### ISSUE TITLE
GPP/Cronus/Titan: device not recognized

### ISSUE THREAD

**Issue by peeezee** [matlo/GIMX#407]
Hi Matlo,

I'm using a Cronus GPP 2508:0001 on a PS4 with the previous DS4 controller generation. With Gimx 5.9 everything worked as expected but now Gimx asserts that no adapter can be found.
Gimx-launcher detects the Cronus.

Thanks for your time,
JP

global option -l with value `log.txt'
global option -c with value `testds4.xml'
controller #1: option -p with value `\\?\hid#vid_2508&pid_0001#6&1f5f238f&1&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}'
now reading arguments for controller #2
status flag is set
subpos flag is set
force_updates flag is set
GIMX 6.1 i386
Windows 10 (or later) x64
Kernel version: 10.0 (10586)
windows/async.c:211 async_open_path: async_init should be called first
No GPP detected.
gimx.c:207 SDL_main: no adapter detected

**Comment by matlo** [comment]
I'll fix this in GIMX 6.2. Thanks for reporting!

**Comment by matlo** [comment]
This should be fixed in GIMX 6.2: https://github.com/matlo/GIMX/releases/tag/v6.2

**Comment by peeezee** [comment]
Thanks, Mat.
