### ISSUE TITLE
g27 wheel+fanatec clubsport pedal on ps4

### ISSUE THREAD

**Issue by doverben** [matlo/GIMX#418]
hi there. 
i was wondering will this combination work with the latest 5.8 firmware with virtual pc? i would like to use a g27 wheel (which works well with its own pedals with previous gimx versions) with fanatec pedals os ps4, assetto corsa. is it possible? with one pc or via usb hub with 2 pcs? 
thanks

**Comment by matlo** [comment]
Using GIMX in virtual machine is not recommended.
Most of your questions will probably be answered in the wiki: https://gimx.fr/wiki/index.php?title=Main_Page
If you have any further questions, please post in the forum, in the GIMX discussion section.
Issues on github should be used to report issues only, not to ask general questions.
