### ISSUE TITLE
Inactivity timeout (command line option)

### ISSUE THREAD

**Issue by hassemlal** [matlo/GIMX#443]
Hi, I have a feature request. Is it possible for gimx to detect when there is no input activity and exit with a specific code. 
It will be very useful to automatically shutdown a raspberry after a period of inactivity. 
Sthg along these lines:
```
#!/bin/bash
/usr/bin/gimx ......
if [ $? -eq 75 ]
then
   halt
fi
exit $?
```

**Comment by matlo** [comment]
Value will be 62 (errno ETIME = Timer expired).

**Comment by matlo** [comment]
I will consider adding a timeout command line option from release 7.0.

**Comment by matlo** [comment]
Return value in case of inactivity timeout will be -4.
Value is defined in core/include/gimx.h in the current development branch.
