### ISSUE TITLE
Random disconnections

### ISSUE THREAD

**Issue by mcdoolz** [matlo/GIMX#461]
I've got a consistent disconnection occurring with my G25, PS4 and a purchased dongle.

I've noted that there have historically been a few people experiencing these disconnections.

https://gimx.fr/forum/viewtopic.php?f=5&t=1930
https://github.com/matlo/GIMX/issues/393

I'm using a genuine PS4 controller, the bought dongle and was using v6.7 of GIMX, now updated to 6.8 and still occurring.

I've attached three log files herein.
[log-g25.txt](https://github.com/matlo/GIMX/files/1123525/log-g25.txt)
[log-g25-2.txt](https://github.com/matlo/GIMX/files/1123527/log-g25-2.txt)
[log-g25-3.txt](https://github.com/matlo/GIMX/files/1123529/log-g25-3.txt)

There is no consistent arrangement of button presses that I've noted to be causing the issues.

None of the posts I've read seem to have any real advice about what is causing the issue or how to mitigate it.
Should I be disabling something?

I've noted that allegedly a Linux system is the way to do it?  I will test it with Linux later, but as I've noted with the other PS4 fellow, the issue wasn't OS related as Win10 seemed to fix his issue.

Thanks again for all your work, I hope you can help me with this issue.

**Comment by matlo** [comment]
There are a few advices here:
https://gimx.fr/wiki/index.php?title=FAQ#21
https://gimx.fr/wiki/index.php?title=FAQ#23

**Comment by mcdoolz** [comment]
Thank you for the response;

> This is probably due to a failure in the authentication process, which requires a DS4 to be wired all the time to the computer.
> This can either be due to a bad USB cable, or the DS4 not being powered off before connecting it to the computer.
> Also make sure you have disabled power saving for the USB devices.

I disabled power saving for every USB device but it still disconnects.  The disconnection is consistent in that it's within a few minutes.

Assuming DS4 to be a typo for PS4?

Insofar as the DS4 being powered off, is this to mean that it's crucial to turn off the PS4 before hooking up the PC or turning off the controller before hooking it up to the PC?

I'm not sure what constitutes a bad usb cable, but if a cable were bad, why would it work, then suddenly not work?

Thanks again for any help you can provide.

**Comment by matlo** [comment]
There's no typo, it won't work if the DS4 communicates with both GIMX and the PS4. Turning it off before connecting it to the computer ensures it won't communicate with the PS4.

Try running GIMX in Linux Mint 18. If it does work either it is very likely to be a hardware fault (bad cable, faulty hardware part, bad contact).

**Comment by mcdoolz** [comment]
What is the DS4?  The dongle?

**Comment by matlo** [comment]
DS4 = Dualshock 4.

**Comment by mcdoolz** [comment]
So in other words, the DS4 should be turned off altogether before it is plugged into the computer, and then when it turns on, there should only be the Logitech Wheel available in controllers?

**Comment by matlo** [comment]
Exactly.

**Comment by mcdoolz** [comment]
Okay, I will give that a shot, as up until now, the PS4 had been displaying both the DS4 **and** the G25.

I will post back.

Thank you for your help and patience.

**Comment by mcdoolz** [comment]
I'm pleased to report that the system is working terrifically!  The issue was in fact that the DS4 was turned on before being plugged into the computer.

Thank you Mathieu, I just finished a few races without a single hiccup and I couldn't be happier.

You are a saviour.
