### ISSUE TITLE
[Windows] Memory leak due to raw input

### ISSUE THREAD

**Issue by assumenothing** [matlo/GIMX#462]
The file `shared/gasync/src/input/windows/rawinput.c` in the function `wminput_handler` has memory that is being allocated, but never freed. This results in GIMX consuming an ever increasing amount of memory and possibly leading to a crash.

**Comment by matlo** [comment]
Thanks for reporting!
This seems to be a regression since GIMX 6.0.
How fast does it leak on your setup?

**Comment by TommunismDotNet** [comment]
Using a hacked together MSVC/Clang debug build it was probably leaking a megabyte every minute (which is probably quite a bit more than a standard release build). I've been using version 6.3 64-bit for a while (for several hours at a time) and I've never had an issue with it running out of memory; though admittedly, I have 16GB of RAM.

**Comment by matlo** [comment]
With a G502 @ 1000Hz the leak is about 3.8 MB every minute with a constant mouse movement.
This is 228MB per hour.
