### ISSUE TITLE
Remove invalid Version key from destop files

### ISSUE THREAD

**Issue by amak79** [matlo/GIMX#466]
The Gentoo Linux package manager automatically runs `desktop-file-validate` (provided by desktop-file-utils on Debian) to ensure .desktop files are correctly formatted.

`config/gimx-config.desktop` and `fpsconfig/gimx-fpsconfig.desktop` fail validation with the following error:

```
$ desktop-file-validate /usr/share/applications/gimx-*.desktop
/usr/share/applications/gimx-config.desktop: error: value "0.25" for key "Version" in group "Desktop Entry" is not a known version
/usr/share/applications/gimx-fpsconfig.desktop: error: value "0.25" for key "Version" in group "Desktop Entry" is not a known version
```

The `Version` key is supposed to be used to specify the desktop entry specification that the desktop file conforms with, and is not required to be present.

According to the [specification](https://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#extending), the GIMX desktop files can pass validation by using the following key/value:

```
X-GIMX-Version=0.25
```

**Comment by matlo** [comment]
Done.
