### ISSUE TITLE
Do not strip binaries

### ISSUE THREAD

**Issue by amak79** [matlo/GIMX#467]
The Gentoo Linux package manager has found the following issues during its automatic QA checks:

```
 * QA Notice: Pre-stripped files found:
 * /usr/lib/libgimxusb.so
 * /usr/lib/libgimxtimer.so
 * /usr/lib/libgimxserial.so
 * /usr/lib/libgimxprio.so
 * /usr/lib/libgimxpoll.so
 * /usr/lib/libgimxinput.so
 * /usr/lib/libgimxhid.so
 * /usr/lib/libgimxuhid.so
 * /usr/lib/libgimxconfigeditor.so
 * /usr/lib/libgimxgpp.so
 * /usr/lib/libgimxupdater.so
 * /usr/lib/libgimxconfigupdater.so
 * /usr/lib/libgimxcontroller.so
```

Gentoo has a [policy](https://wiki.gentoo.org/wiki/Project:Quality_Assurance/Backtraces#Stripping) that requires packages to leave the task of stripping to the package manager. Would you consider disabling stripping binaries i.e. removing `-s` from the makefiles?

**Comment by matlo** [comment]
Done.
