### ISSUE TITLE
GIMX installs libraries without proper .so names/symlinks

### ISSUE THREAD

**Issue by amak79** [matlo/GIMX#468]
The Gentoo Linux package manager has found the following issues during its automatic QA checks:

```
* QA Notice: The following shared libraries lack a SONAME
 * /usr/lib/libgimxconfigeditor.so
 * /usr/lib/libgimxconfigupdater.so
 * /usr/lib/libgimxcontroller.so
 * /usr/lib/libgimxgpp.so
 * /usr/lib/libgimxhid.so
 * /usr/lib/libgimxinput.so
 * /usr/lib/libgimxpoll.so
 * /usr/lib/libgimxprio.so
 * /usr/lib/libgimxserial.so
 * /usr/lib/libgimxtimer.so
 * /usr/lib/libgimxuhid.so
 * /usr/lib/libgimxupdater.so
 * /usr/lib/libgimxusb.so
```

GIMX installs libraries without proper .so names/symlinks which is against Gentoo [policy](https://dev.gentoo.org/~zmedico/portage/doc/ch07s04.html). Are these libraries loaded only at runtime i.e. plugins, or are they linked against? If they are loaded at runtime, the QA notice can be silenced by the package manager. If they are linked against, would it be possible to have these libraries installed with the correct .so names/symlinks?

**Comment by matlo** [comment]
This makes sense when the library is shared by multiple packages. These libraries are shared by the gimx binaries only and they belong to the same package. There is no way to have the ABIs misaligned.

**Comment by amak79** [comment]
In that case the QA notice can be safely silenced by the package manager. Thank you.
