### ISSUE TITLE
config editors can crash if locale 'en_GB' misses

### ISSUE THREAD

**Issue by amak79** [matlo/GIMX#469]
When starting `gimx-fpsconfig` I get the following message:

```
18:20:48: Cannot set locale to language "English".
18:20:48: locale 'en_GB' cannot be set.
18:20:48: Cannot set locale to language "English".
18:20:48: locale 'en_GB' cannot be set.
18:20:48: Cannot set locale to language "English".
18:20:48: locale 'en_GB' cannot be set.
18:20:48: Cannot set locale to language "English".
18:20:48: locale 'en_GB' cannot be set.
18:20:48: Cannot set locale to language "English".
18:20:48: locale 'en_GB' cannot be set.
18:20:48: Cannot set locale to language "English".
18:20:48: locale 'en_GB' cannot be set.
18:20:48: Cannot set locale to language "English".
18:20:48: locale 'en_GB' cannot be set.
18:20:48: Cannot set locale to language "English".
18:20:48: locale 'en_GB' cannot be set.
```
My current available locales are:
```
$ locale -a
C
en_AU
en_AU.iso88591
en_AU.utf8
POSIX
```

Adding the `en_GB` locale makes the message go away. Is there a reason why `gimx-fpsconfig` needs the `en_GB` locale? I don't have this issue with `gimx-config` or `gimx-launcher`.

**Comment by matlo** [comment]
The configs use '.' as a decimal separator. The apps temporarily change the locale to en_GB in code sections that handle numbers with a decimal separator, to ensure numbers can only have '.' as a decimal separator. It is a mistake as this locale may not  be available. This definitely needs to be fixed.

**Comment by matlo** [comment]
I just tried GIMX 6.8 without the en_GB locale on my system. It makes gimx-config crash.
