### ISSUE TITLE
Do not assume libraries should be installed in $(prefix)/lib

### ISSUE THREAD

**Issue by amak79** [matlo/GIMX#475]
Gentoo Linux has a QA check that prevents the package manager from installing 64-bit libraries into anything other than `(/usr)/lib64`. Many Makefiles assume that their libraries should go to `/usr/lib`, or `$(prefix)/lib`. This assumption can cause a serious mess if `/usr/lib` isn't a symlink to `/usr/lib64` on 64-bit systems.

In GIMX, this can be fixed by setting `libdir` in `shared/Makedefs` from:
```
libdir = $(exec_prefix)/lib
```
to:
```
libdir = $(exec_prefix)/$(LIBDIR)
```

**Comment by amak79** [comment]
I forgot to mention that $LIBDIR is undefined and needs to be set. One way to do this is with the following:
```
MACHINE := $(shell uname -m)

ifeq ($(MACHINE), x86_64)
LIBDIR = lib64
endif
ifeq ($(MACHINE), i686)
LIBDIR = lib
endif
``` 
Other cases may also need to be checked such as `i386`.

**Comment by amak79** [comment]
Since GIMX supports ARM as well, this will require even more checks. If this is too much effort, I can work around this issue in the Gentoo package.

**Comment by matlo** [comment]
Thanks for reporting. Not sure I'll have some time to fix this.

**Comment by amak79** [comment]
I was able to fix this in the Gentoo package. You can close this issue if you want.
