### ISSUE TITLE
gimx crashes when input method is physical devices

### ISSUE THREAD

**Issue by N4styVillian** [matlo/GIMX#495]
Could someone help?
I am using the GIMX Adapter, installed all software and firmware for G27. Also installed Logitech drivers.
I am attempting to use an Accuforce wheel for Forza etc
Everytime i launch the Config editor it crashes: here is my event log
```
Log Name:      Application
Source:        Application Error
Date:          10/11/2017 18:26:32
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      xxxx
Description:
Faulting application name: gimx-config.exe, version: 6.10.0.0, time stamp: 0x59f0c8e8
Faulting module name: ntdll.dll, version: 10.0.16299.15, time stamp: 0x493793ea
Exception code: 0xc0000374
Fault offset: 0x00000000000f87bb
Faulting process ID: 0x4394
Faulting application start time: 0x01d35a516841f9ec
Faulting application path: C:\Program Files\GIMX\gimx-config.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report ID: 65a6cea8-8cde-41ee-b331-54b911587e5d
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-11-10T18:26:32.451173100Z" />
    <EventRecordID>9121</EventRecordID>
    <Channel>Application</Channel>
    <Computer>xxxxx</Computer>
    <Security />
  </System>
  <EventData>
    <Data>gimx-config.exe</Data>
    <Data>6.10.0.0</Data>
    <Data>59f0c8e8</Data>
    <Data>ntdll.dll</Data>
    <Data>10.0.16299.15</Data>
    <Data>493793ea</Data>
    <Data>c0000374</Data>
    <Data>00000000000f87bb</Data>
    <Data>4394</Data>
    <Data>01d35a516841f9ec</Data>
    <Data>C:\Program Files\GIMX\gimx-config.exe</Data>
    <Data>C:\Windows\SYSTEM32\ntdll.dll</Data>
    <Data>65a6cea8-8cde-41ee-b331-54b911587e5d</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>
```
I also have the same issue with the launcher:

```
Log Name:      Application
Source:        Application Error
Date:          10/11/2017 18:38:19
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      xxxxx
Description:
Faulting application name: gimx.exe, version: 0.0.0.0, time stamp: 0x59f0c8ec
Faulting module name: ntdll.dll, version: 10.0.16299.15, time stamp: 0x493793ea
Exception code: 0xc0000374
Fault offset: 0x00000000000f87bb
Faulting process ID: 0x1f08
Faulting application start time: 0x01d35a5313e09735
Faulting application path: C:\Program Files\GIMX\gimx.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report ID: 4e33a194-a38c-46ac-8285-e33b1d04c4a7
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-11-10T18:38:19.597611700Z" />
    <EventRecordID>9129</EventRecordID>
    <Channel>Application</Channel>
    <Computer>xxxxxx</Computer>
    <Security />
  </System>
  <EventData>
    <Data>gimx.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>59f0c8ec</Data>
    <Data>ntdll.dll</Data>
    <Data>10.0.16299.15</Data>
    <Data>493793ea</Data>
    <Data>c0000374</Data>
    <Data>00000000000f87bb</Data>
    <Data>1f08</Data>
    <Data>01d35a5313e09735</Data>
    <Data>C:\Program Files\GIMX\gimx.exe</Data>
    <Data>C:\Windows\SYSTEM32\ntdll.dll</Data>
    <Data>4e33a194-a38c-46ac-8285-e33b1d04c4a7</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

Problem signature:
P1: gimx-launcher.exe
P2: 6.10.0.0
P3: 59f0c8e1
P4: StackHash_ffbb
P5: 10.0.16299.15
P6: 493793ea
P7: c0000374
P8: PCH_82_FROM_ntdll+0x00000000000A0994
P9: 
P10: 
```

Any ideas?

**Comment by matlo** [comment]
Is there any similar entry for other app in the event log?

Does this also happen with all devices unplugged from computer?

**Comment by N4styVillian** [comment]
Let me try with all devices unplugged

**Comment by N4styVillian** [comment]
same issue with all devices unplugged
cant find any other app issues in event log? is there anything specific i should be looking for?

**Comment by matlo** [comment]
Hi,

Could you please generate a crash dump for gimx.exe?
There are details on how to achieve this here: https://kb.acronis.com/content/27931

**Comment by N4styVillian** [comment]
Will do. I’m stateside now so later

Merry Christmas

**Comment by matlo** [comment]
Hi,

I think I may have fixed the crash, but I'm unsure as I am not reproducing on my setup.

Could you please test the following GIMX 7.0 beta?

https://gimx.fr/download/2a7c5e3baff947fda9ff52061cf4ba5763c795c2/gimx-7.0-x86_64.exe

**Comment by N4styVillian** [comment]
Ok buddy
Will try tomorrow

**Comment by N4styVillian** [comment]
i have managed to get it to load
It has detected my Accuforce wheel and i am able to configure most of the
buttons in game however, i cant get the software to see my Fanatec pedals,
any suggestions?

**Comment by matlo** [comment]
Did you add your pedal axes in the axis tab?

**Comment by N4styVillian** [comment]
use auto detect?

**Comment by N4styVillian** [comment]
keeps failing to detect when i press the pedals, clutch, brake and gas

**Comment by matlo** [comment]
This may be a regression. Let me check this.

**Comment by N4styVillian** [comment]
Ok illl be back in 1hr to help troubleshoot

**Comment by matlo** [comment]
Please install GIMX 6.11 and make a backup of the SDL2.dll file. Then install the GIMX 7.0 beta and replace the SDL2.dll file, and try again.

**Comment by N4styVillian** [comment]
the application was unable to start correctly (oxoooooo7b)

**Comment by matlo** [comment]
Are you sure you are not mixing 32bit and 64bit binaries?

**Comment by N4styVillian** [comment]
ah, let me check

**Comment by matlo** [comment]
I just replaced the beta version with another one (same link).
It turns out the SDL2 library has the same bug that can cause random issues like a crash (in the worst case).

**Comment by N4styVillian** [comment]
Ok

**Comment by N4styVillian** [comment]
I can run the config file
but when i launch gimx.exe
and click start (messages none, grab mouse unchecked), input windows events
(all other options crashes)
 I get this message clicking start:

src/windows/gprio.c:23 gprio: failed to set priority class
global option -c with value `LogitechG27_G29 modfied.xml'
controller #1: option -p with value `COM3'
now reading arguments for controller #2
grab flag is unset
subpos flag is set
force_updates flag is set
window_events flag is set
GIMX adapter detected, controller type is: G27 PS3.
Reset sent to the GIMX adapter.
no pass-through device is needed
Start the game with a dualshock 3, and then reassign game controllers.
using default refresh period: 10.00ms
Warning: joystick not found: Logitech G27 Racing Wheel USB 0
Warning: macros are not available for: joystick FANATEC ClubSport USB
Adapter (shifter mode) (0)
Warning: can't open macro directory
C:\Users\lbarn\AppData\Roaming//gimx//macros/
Timer resolution: min=156250 max=5000 current=5007
rounding timer period to 9513

clicking check - app crashes

**Comment by matlo** [comment]
I believe I finally fixed this issue.
Please try this beta version: https://gimx.fr/download/7a29b9ead9b069ba5692932347b447d9545daa7b/gimx-7.0-i386.exe
And let me know if it still crashing.

**Comment by N4styVillian** [comment]
Selected physical device no crash

But I do get mouse not detected – should I be concerned with that?

 

Thanks

 

Laud

**Comment by matlo** [comment]
You mean, gimx-config does not detect mouse buttons?

**Comment by N4styVillian** [comment]
Yes

**Comment by matlo** [comment]
Could you please run ginput_test.exe from C:\Program Files (x86)\GIMX?

1. Select physical for the mouse and keyboard input method (type 1 and press enter).
2. Check detected mouse and keyboards.
3. Press mouse buttons.
4. Press esc.
5. Do steps 1-4 again.

**Comment by N4styVillian** [comment]
This is the message I get
when I run the check or start I get the following dialogue but not able to
use my mouse
I have to alt-tab to get mouse functioning
[image: Inline image 1]

**Comment by matlo** [comment]
The image was removed by github. Please send it to mat.lau[at]laposte.net.

**Comment by redion1992** [comment]
Can you check if there is a tick next to "Window events" in the Advanced menu of Gimx-config? When I enable it, it seems to give similar issues. Try turning it off as well.

**Comment by N4styVillian** [comment]
Thanks, there is now tick next to windows events

Baffling, no idea what to do ☹

**Comment by matlo** [comment]
Could you please run ginput_test.exe from C:\Program Files (x86)\GIMX and post the command output?

1. Select physical for the mouse and keyboard input method (type 1 and press enter).
2. Check detected mouse and keyboards.
3. Press mouse buttons.
4. Press esc.
5. Do steps 1-4 again.
