### ISSUE TITLE
7.0beta4 i386 Fails to work with PS4

### ISSUE THREAD

**Issue by GodlikeRU** [matlo/GIMX#517]
I tested 6.9 and it works fine using the same configuration so it must be 7.0 issue.

When running gimx it says it's introduction about config and blah blah then mass spam with error message appears `src/sdl/sdlinput.c:756 sdl_peep_events: SDL_PeepEvents failed with error: The event system has been shut down`

The same program works fine with X360. It's not possible to continue as it's not working on PS4 (no input). It does not crash however.

Attaching log + drmemory run - [DrMemory-gimx.exe.9688.000.zip](https://github.com/matlo/GIMX/files/1648782/DrMemory-gimx.exe.9688.000.zip)

Additional info:
PS4 5.01
Arduino Leonardo chinese clone USB DIY
Windows 10 1607 x64
GIMX 7.0beta4 i386 with drmemory
Wolfenstein 2 config from forum

**Comment by matlo** [comment]
Fixed by matlo/gimxinput@a8ea1a7bd9fcc624c157956e7cd538936c914c9f
