### ISSUE TITLE
libwxgtk3.0-0 - libwxgtk3.0-0 not avaliable in raspberry (Raspbian 2017-11-29)

### ISSUE THREAD

**Issue by ivan113** [matlo/GIMX#520]
When try to install GIMX 6.11-1 (sudo dpkg -i gimx.deb) the console showed me:
**dpkg: problemas de dependencias impiden la configuración de gimx:
 gimx depende de libwxbase3.0-0 (>= 3.0.2); sin embargo:
  El paquete `libwxbase3.0-0' no está instalado.
 gimx depende de libwxgtk3.0-0 (>= 3.0.2); sin embargo:
  El paquete `libwxgtk3.0-0' no está instalado.**

If i try to install libwxbase3.0-0 the raspbian tell me that there is a new version avaliable, libwxbase3.0-0v5, with libwxgtk3.0-0 too happend.

there is some solution?

**Comment by matlo** [comment]
`sudo apt-get -f install`

**Comment by ivan113** [comment]
When i make this, in my version of Raspbian, i can't update the packages libwxbase3.0-0 and libwxgtk3.0-0.

It's posible that the version of Raspbian is the reason? Can be the Raspbian 2017-11-29 too new to GIMX 6.11-1?

**Comment by matlo** [comment]
Did you try the stretch package?
https://github.com/matlo/GIMX/releases/download/v6.11/gimx_6.11-1_armhf_stretch.deb
