### ISSUE TITLE
gimx-fpsconfig loads wrong shape for DZ

### ISSUE THREAD

**Issue by GodlikeRU** [matlo/GIMX#525]
I found a bug in gimx-fpsconfig. If you save a config with `shape="rectangle"` then in gimx-fpsconfig dropdown shape will still be on `circle` value and it will overwrite actual config value on save.

Steps to reproduce:
1. Make a config with `shape="rectangle"` and save it.
2. Open it in gimx-fpsconfig - wrong shape value will be displayed, always  `Circle` . If you hit Save then always `Circle` shape will be written to the config.

Using Gimx7.0beta6
Attaching config file to test
[PS4_InfamousSecondSon_Godlike.zip](https://github.com/matlo/GIMX/files/1691915/PS4_InfamousSecondSon_Godlike.zip)

**Comment by GodlikeRU** [comment]
`if(id.find("stick") == string::npos)
    {
        m_TempEvent.SetShape("");
    }`

code in `GIMX/shared/gimxconfigeditor/src/XmlReader.cpp` on line **259** is causing this

**Comment by matlo** [comment]
Having a dead zone shape only makes sense for sticks, and at the beginning there was a single controller emulation (joystick, for ps3). The check should now be "if axis is not in rel_axis_0 to rel_axis_3".

**Comment by matlo** [comment]
I just made a fix that also handles old configurations.
