### ISSUE TITLE
Gimx input problems :(

### ISSUE THREAD

**Issue by Gamerios** [matlo/GIMX#527]
# Hello

**I done 3 DIY GIMX UDB Adapters.**

**All are working 1 Xbox One , 1 Xbox 360, and 1 for PS4**

**_The problem i have the when at gimx tryed at many different versions gimx 6.11  the newest ,6.10 and much more when using_** 

**Input Physical deivces i get at start this errors:**
**windows/rawinput.c:443 get_dev_name_by_instance: SetupDiGetDeviceRegistryProperty failed with error: Die Daten sind unzul**
**windows/rawinput.c:443 get_dev_name_by_instance: SetupDiGetDeviceRegistryProperty failed with error: Die Daten sind unzul**

**And then windows error that gimx not work anymore :(**

At all **3 consoles**  so i think it has **something todo** with G**imx at PC**

**when i use at Input Window events all is working.**

**But with Window events when i then use the PC th emouse or keyboard the CMD window is not in focus anymore and controller then not works anymore :(**

**WHat can i do ?   to fix this problem** 

**I searched much hours at google but find nobody with this problem or anything that helps.**

**My OS Windows 10 Pro x64** 

_Thank you

Regards_

**Comment by matlo** [comment]
Please try GIMX 7.1 and let me know if it fixes your issue.

**Comment by Gamerios** [comment]
Where i can find it ?

**Comment by matlo** [comment]
Here: https://github.com/matlo/GIMX/releases
Or in gimx-launcher, click on "Help > Update".

**Comment by matlo** [comment]
Closing due to missing user feedback.
