### ISSUE TITLE
Include git submodules in archive releases

### ISSUE THREAD

**Issue by amak79** [matlo/GIMX#532]
The 7.1 release archive doesn't include the Git submodules, because GitHub doesn't support it. This makes it somewhat useless for distro packaging.

I have attempted to create a release archive manually with `git archive`, but it also doesn't include Git submodules because `git archive` doesn't have a `--recursive` option.

```
git checkout v7.1
git submodule update --init
git archive --format=tar.gz --prefix=GIMX-7.1/ --output=GIMX-7.1.tar.gz v7.1
```
I was able to use GNU tar (1.29) to create a release archive, although the top level directory in the archive is "GIMX" and not "GIMX-7.1":
```
git checkout v7.1
git submodule update --init
tar -cvaf GIMX-7.1.tar.gz --exclude-vcs ../GIMX
```

**Comment by matlo** [comment]
Ok I uploaded a source archive with release v7.2. I plan to provide source archive for further versions. Let me know if there is anything wrong with it.
