### ISSUE TITLE
Gimx 7.1 - DFGT reduced steering range

### ISSUE THREAD

**Issue by ricardomat** [matlo/GIMX#534]
After upgrading gimx from 6.11 to 7.1 version, my Driving Force GT wheel running as G29, had it's steering angle range reduced significantly. I didn't measure how much of loss in degrees I had, but I guess it's about 2/3 loss. Setting messages to debug, it is possible to see that after few degrees of steering, the messages stop printing before reaching the wheel's end of course. Downgrading back to 6.11 the wheel resumed to work normally to its previous behaviour.

**Comment by matlo** [comment]
Please update to version 7.2 and let me know if it fixes your issue.

**Comment by lunohod** [comment]
I also had issues with 7.1, but 7.2 is working fine with my DFGT wheel.

**Comment by matlo** [comment]
Closing as this should be fixed in 7.2. Please reopen if it is not.

**Comment by ricardomat** [comment]
I upgraded to 7.2, and it is working fine now. Thanks.
