### ISSUE TITLE
Windows UWP Skype notification break input grab

### ISSUE THREAD

**Issue by GodlikeRU** [matlo/GIMX#543]
I would like to report pretty annoying bug. Whenever  new message UWP notification of Skype appears mouse is freed from gimx and program doesn't capture it anymore until restart.

Steps to reproduce

1. Install UWP Skype
2. Run gimx-launcher and launch gimx
3. Send Message using Skype to get notification
4. GIMX will lose input upon receiving notification

Using GIMX 7.2 x64

**Comment by matlo** [comment]
To be checked before releasing 7.10.

**Comment by matlo** [comment]
Fixed updating Skype.
