### ISSUE TITLE
windows OS scaled screen unable to lock the mouse

### ISSUE THREAD

**Issue by mynameismu12332** [matlo/GIMX#549]
I use a 27 inch 4K screen in  Windows 10 OS.
Display setting I set  to 150% scale. that made the Grab mouse  function unable to run correctly.

If I hold right mouse and move the mouse at a large range, mouse will out of the cmd window and all 
 control functions will be disabled,that will make the control to ps4 halted

edit:seems no more have this issue, close this .

**Comment by matlo** [comment]
Maybe you had some task manager opened?
