### ISSUE TITLE
Mouse translation: stick locked to top and/or left

### ISSUE THREAD

**Issue by dn1973** [matlo/GIMX#563]
Hi Matlo

I just installed your new version of GIMX (7.4).

Unfortunately I am facing some issues while playing Battlefield 1 with mouse (G502) and Sony Navigation Controller (which I was doing for months without any issues).
 
Suddenly, in the middle of the game the crosshair get vertical up to the sky. In some cases the crosshair starts moving in a circle afterwards. 

This happens periodically (estimated every 2-5 minutes). At the moment I cannot say, if this is triggered by a certain mouse movement or not. Anyway, this behaviour makes it hard to play BF1 normally.

What could be the reason behind? Do you have an idea?
Please do not hesitate to contact me if you need further information.

Take care!

**Comment by matlo** [comment]
Hello,

Thanks for reporting.

Which GIMX version did you use before?

Please generate a log file:

1. Select "Messages>Log file" in gimx-launcher before starting GIMX.
2. Reproduce the issue while generating the log file.
3. Stop GIMX, post the log file on pastebin and post the link.

**Comment by dn1973** [comment]
Hi Mathieu!

Just to give you an update: I made a complete new install of Linux Mint 18.3 and GIMX 7.4.
Unfortunately I am facing the same issues while playing BF1 (and also BF4 or CoD:WW2) with my config.
I also try to make the tests with and without macros - result is the same...

Furthermore I am still not able to create a log file with gameplay data... same error as mentioned above. Logging stopped immediately after start.

**Comment by matlo** [comment]
Hi dn1973,

I fixed the log file issue. Please try again with the following test package: https://gimx.fr/download/5110539b3f7361fdd3ffbea40d62a1f85357759f/gimx_7.4-1_amd64.deb

**Comment by dn1973** [comment]
Hi Mathieu!

Perfect - this version works. I was able to create the log file with gameplay data: https://pastebin.com/nX7Uehnw
 
As pastebin only allows 512 kb for free users I cut some data out of the log file. Hopefully this is ok for you. You will find (..) in the log file as a placeholder for gameplay data without any issue.

The error occurred right at the end of the log file.

Hope this helps to find the error! Good luck! ;-)

And thanks a lot for helping me - GIMX is very cool! ;-) 

Best regards
Dominik

**Comment by matlo** [comment]
Thanks. Could you please make another one? I need some extra messages. Select "debug" in the "Messages" drop-down menu, then select "Log file" and check "config".

**Comment by dn1973** [comment]
Hi Mathieu!

Here is the requested file - as before: I cut some data out of the log file.
https://pastebin.com/HvZWh0PY

Good luck!
Dominik

**Comment by matlo** [comment]
Thanks. It should be fixed in this new version: https://gimx.fr/download/5110539b3f7361fdd3ffbea40d62a1f85357759f/gimx_7.4-1_amd64.deb

**Comment by dn1973** [comment]
Hi Mathieu!

Just played CoD:WW2 for almost an hour - without any problems!
Congratulations! You solved the problem!

I will try with BF1 tonight. 

BR,
Dominik

**Comment by dn1973** [comment]
Hi again!

I just want to confirm that I can play BF1 without any issues, too!
Definitely solved!

Dominik
