### ISSUE TITLE
After several hours GIMX doesn't work on Raspberry  

### ISSUE THREAD

**Issue by wjokerw** [matlo/GIMX#573]
Hi, I am using GIMX to connect my hid device(the hid device was mapped to joy up) to ps4.
But after serveral hours, it seems my device lose connection to ps4 but the process still exist.
And I replug my ds4, it still not work until I kill gimx and restart gimx. 
Any suggestion about what leads the problem?

**Comment by matlo** [comment]
It's hard to say without a log file!

```
  --log filename: write messages into a log file instead of the standard output.
    filename: The name of the log file, in the ~/.gimx/log directory (make sure this folder exists).
```

**Comment by matlo** [comment]
Closing due to lack of input. If you can provide a log file please reopen.
