### ISSUE TITLE
Does GIMX support virtual joystick?

### ISSUE THREAD

**Issue by cwlmyjm** [matlo/GIMX#577]
Hi, I am now using GIMX on my Raspberry Pi with DS4.  But I found that I need a micro usb to connect my controller to Pi, that is not convenient. Now I found a driver called ds4drv, which use bluetooth to connect the controller and create a virtual joystick. After trying that program, gimx told me that it cannot find game controller on USB ports. So I am consider that does gimx only support USB devices  or it must need a game controller to pass sony auth? If not, is that possible to decteced virtual joystick without any game controller? Hope you can give me some idea~

**Comment by matlo** [comment]
Hi,
You may want to try the bluetooth connection method, which uses bluetooth to connect both the PS4 and the DS4 to the computer.
https://gimx.fr/wiki/index.php?title=Guide&platform=ps4&connectiontype=BT&ostype=linux&device=Pad
