### ISSUE TITLE
GIMX blutooth connection

### ISSUE THREAD

**Issue by wjokerw** [matlo/GIMX#578]
Hi, I try to uses bluetooth to connect both the PS4 and the DS4 to the computer.I downloaded the latest GIMX software v7.6. I follow the instructions in the wiki. In Step 2, I can not find the Item about "Bluetooth / PS4".

![wiki](https://user-images.githubusercontent.com/24243969/42570677-41b02d84-8547-11e8-9324-385b96278262.png)
![my_gimx_launcher](https://user-images.githubusercontent.com/24243969/42570681-448883da-8547-11e8-83cf-6c48fb5bccfe.png)

**Comment by matlo** [comment]
Please read the requirements section. These instructions are not applicable to the Windows operating system.
