### ISSUE TITLE
【HELP】program not responding

### ISSUE THREAD

**Issue by cnboy1997** [matlo/GIMX#579]
avrdude.exe shows that“the programmer is not responding”then shows that “failed to load firmware” when I want to update firmware. Could you please help me fix this? Thx!

**Comment by matlo** [comment]
Please describe the steps you are following, as well as the hardware you are using.

**Comment by cnboy1997** [comment]
My hardwares are ‘Arduino Leonardo R3 ATMEGA32U4 、and CP2102 usb to ttl’. First I keep arduino plugged into computer then run loader.exe to load my hardware(I play ps4) when it lets me unplug/replug usb I plug CP2102 into computer. Then the problem comes out.

**Comment by matlo** [comment]
Please follow the on-screen instructions to the letter. Both sides of the adapter have to be plugged to the computer. When requested, you have to unplug and replug the Arduino side.

**Comment by cnboy1997** [comment]
I did this for several times but it shows no new device found

**Comment by matlo** [comment]
This probably means the wiring is incorrect. It  the wiring is incorrect or the CP2102 side is not powered, then the Arduino will not enter into programming mode when replugging it.
