### ISSUE TITLE
Illegal Copy report.

### ISSUE THREAD

**Issue by ali-soltani** [matlo/GIMX#588]
Hello.
There is a company in iran in the name "game box adapter" that selling people your products with multiplied by 6 from real price of materials. 
I knew it but was not sure. Until that i found your wiki page on their site. 
I didn't know how to tell you and this is the only way that i could contact you.
This guy is a millionaire now.
By the way i found a lot of dudes that making the same stuff and selling over priced but no prof on them.
What do you want to do with them?

**Comment by matlo** [comment]
Hello,

GIMX is open-source software and "open-source design". This allows anyone to build and sell copies.

What's wrong with these dudes is that they are claiming authorship and using copyrighted documentation.

I have no intention to waste any time on this.
