### ISSUE TITLE
Problem to upgrade to version 7.9

### ISSUE THREAD

**Issue by dn1973** [matlo/GIMX#591]
Hi Mathieu!

I just tried to upgrade GIMX to the newest version 7.9 and get the follwing error right after downloading: 

**Error: Dependency is not satisfiable: libwxbase3.0-0v5 (>= 3.0.4+dfsg)**

GIMX is running on Linux Mint 18.3 "Sylvia" with the latest patch level. (I updated it a few days ago)

GIMX 7.8 is still running fine.

Any idea how to solve this issue? 
Please let me know if you need any more information.

Best regards
Dominik

**Comment by matlo** [comment]
Hi Dominik,

Starting from version 7.9 the only supported x86 GNU/Linux distribution is Ubuntu 18.04 (and derivatives such as Linux Mint 19). Ubuntu 16.04 is no more supported.

I forgot to add this in the announcement. I just fixed this.

**Comment by dn1973** [comment]
Hi Mathieu!

Ok, thanks for your prompt answer! 
Then I will upgrade to Linux Mint 19 as I am only using Linux this for GIMX!

Have a nice day!
Dominik
