### ISSUE TITLE
No response from socket API 

### ISSUE THREAD

**Issue by CJFreePy** [matlo/GIMX#592]
It works via cmd command on win7 X64, but no response from socket API.
CMD works find:
  `subprocess.Popen('c:/program files/gimx/gimx.exe --event "PS(255)" -d 192.168.2.19:51914')`

Socket API, no response:
`addr = ('192.168.2.19',51914)
baseReq = b'0x00,0x00'  

with socket.socket(socket.AF_INET,socket.SOCK_DGRAM) as s:
	print('go.')
	s.sendto(baseReq,addr)
	print(s.recv(1024))
	print("end.")
	s.close() `

also no action/response for click (is this right format?):
`clickRIGHT = b'0x01,0x01,0x84,0xff,0x00,0x00,0x00'`

screen print (always in waiting end) : 
`go.
`

Thanks!

**Comment by matlo** [comment]
Does any message show up the the remote instance window?

**Comment by CJFreePy** [comment]
for Socket method:
  none logs  

for cmd method: 
![v_l qwa 8 e sqlu gv j d](https://user-images.githubusercontent.com/34242115/45462699-79d8b980-b73b-11e8-8515-512e48c92436.png)

**Comment by matlo** [comment]
Try using wireshark to compare the data sent by your code with the data sent by GIMX.

**Comment by matlo** [comment]
Closed due to inactivity.
