### ISSUE TITLE
Makefile fails if space in directory

### ISSUE THREAD

**Issue by CodeOhms** [matlo/GIMX#597]
If the project is under a directory with a space anywhere in it, the project fails.
For example, under my system I discovered this bug with a directory like:
`C:\Users\User\Common Locations\Programming\GIMX`

The reason the project fails is that one of the makefiles attempts to create a `.dll` called `libCommon.dll`.
Essentially, the makefile at fault stops where the first space occurs, and takes all characters from there back to the previous slash.

This isn't a big issue. I just want to let people know to avoid spending hours trying to debug this issue like I did.

**Comment by matlo** [comment]
Please provide a console output showing the error.

**Comment by matlo** [comment]
I think changing this line:
https://github.com/matlo/GIMX/blob/84b66c744ab3200cbc89c74e47e1fe828ed84de7/shared/Makedefs#L16
to:
`LIBNAME=lib$(shell basename "$(shell pwd)")`
may fix the issue.

**Comment by matlo** [comment]
Fixed in master and submodules.
