### ISSUE TITLE
Arduino UNO firmware needed

### ISSUE THREAD

**Issue by aegelsky** [matlo/GIMX#599]
Hi.

Looks like with this - https://www.instructables.com/id/Make-arduino-uno-work-like-leonardo/
we can get HID support on UNO (which is much more common board that Leonardo).
Also it's main chip is not too different from Leonardo.
I've tried to flash it with your current hex (for atmega32u4) and got no luck yet.
Can you share source of firmware G29PS4 so I could compile and test in on UNO with that HID fix?
I have PS4 and G27 and with NY holidays and armageddon in russian post system I won't get Leonardo sooner that Jan or Feb(
Or at least of you don't want to share it, could you make a hex(es) for UNO?
That HID fix looks promising.

Best regards,
Alexander.

**Comment by aegelsky** [comment]
found firmware, you got it shared, my bad.
how can I get this working on UNO?
use that fix for HID and make firmware for it's chip and it should work?

**Comment by matlo** [comment]
Hi,

Sadly non-atmega32u4 firmware are known to have issues, and I don't have enough time to fix them :(
