### ISSUE TITLE
how can i pick weapon at 1 o'clock in HorizonZeroDawn with macro?

### ISSUE THREAD

**Issue by vulntor** [matlo/GIMX#627]
use maxis can only pick up weapon in 12、6、9 o'clock，but in this game i net to pick up weapon at 1 o'clock 
so i tried
MACRO KEYDOWN F1     
JAXIS 2 30000
KEYDOWN F1  

buit nothing happend when i press F1 

i use auto detect to find the axis  number，am i right? it show me axis id is 2
how to find the location number? 
how to move rstick to point at 1 o'clock?

**Comment by matlo** [comment]
This is not the right place for this kind of question. Please go to the forum instead.

**Comment by vulntor** [comment]
> This is not the right place for this kind of question. Please go to the forum instead.

i didn't find an answer in wiki nor in forum
