### ISSUE TITLE
"Can't retrieve configs list!" error.

### ISSUE THREAD

**Issue by CodeOhms** [matlo/GIMX#634]
The gimx-launcher program throws the error "Can't retrieve configs list!" when attempting to get new configs. This also occurs in my config dl util that I've been fixing in my little spare time.
Upon further inspection, I found that the ConfigUpdater module returns the error -2, meaning initialisation failed.

The problem is present in both the master and gimxfile branches. Tested on two different linux machines, each running 64 bit Manjaro Linux.

**Comment by matlo** [comment]
Thanks for reporting. This only happened in the gimxfile branch, and I just fixed it.
