### ISSUE TITLE
Does it work with 8Bitdo Wireless Bluetooth USB Adapter?

### ISSUE THREAD

**Issue by YanDevDe** [matlo/GIMX#642]
Since GIMX can emulate PS3 or PS4 controller per Bluetooth, I assume it should work with **8Bitdo Wireless Bluetooh USB Adapter** so then you can use PS3/PS4 "controller" on Nintendo Switch.
Did someone tried that before? 

I might give GIMX a shot if 8Bitdo would work. 😄

**Comment by matlo** [comment]
Such questions should be posted on the forum, not in the issue tracker.

It is not an officially supported use case, and I am not aware of anyone that tried that.
