### ISSUE TITLE
Gimx-config does not detect axis for Fanatec CSL Elite PS4

### ISSUE THREAD

**Issue by lmirel** [matlo/GIMX#644]
I'll need to update this to confirm if the issue is related to the Logitech compat mode for the Fanatec wheel or if it is general.
It seems this is due to the way the event detection works in gimx-config. Hexdump on the hidraw for the wheel (in Linux) updates accordingly.
I'll see if/how I can help with this. Any ideas welcome, I know time is a luxury.

**Comment by matlo** [comment]
Hi Mirel,
Please check with jstest (or jstest-gtk) if wheel axis is correctly detected and calibrated.

**Comment by lmirel** [comment]
hi Mat,
I checked all modes with jstest and none update any axis. it reports 8 axis but none show any change when turning the wheel or pressing pedals. jscal doesn’t seem to help either. I’ll need to check other options.
is this the first time you hear about this kind of behavior?
thanks

**Comment by matlo** [comment]
I wouldn't be surprised that the compat mode has issues on Linux.
Unplug/replug the wheel and check the output of the dmesg command.

**Comment by lmirel** [comment]
actually, none of the modes work on Linux. jtest is unable to handle any axis on any mode on linux.
the wheel has 3 modes exposing 3 different PIDs: 2 of them as Ender AG and one (compat) mode with Logitech PID.
anyway, none of these modes expose axis supported by jtest and as such they won't work 'as is'.
I'm assuming GIMX uses the same approach similar to jtest for reading events.

**Comment by matlo** [comment]
Wheel support on Linux is very sparse. Issue could be some unexpected behavior of the Logitech compat mode, like some missing USB string descriptors (iVendor / iProduct). Did you check dmesg output for any error?

**Comment by lmirel** [comment]
there is a missing product descriptor (empty string), how is this a problem?
Bus 001 Device 111: ID 046d:c260 Logitech, Inc.
[7614239.253165] usb 1-1.1.2: new full-speed USB device number 114 using dwc_otg
[7614239.387331] usb 1-1.1.2: New USB device found, idVendor=046d, idProduct=c260
[7614239.387337] usb 1-1.1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[7614239.387341] usb 1-1.1.2: Manufacturer: Fanatec
[7614239.390396] input: Fanatec as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.1/1-1.1.2/1-1.1.2:1.0/0003:046D:C260.0069/input/input104
[7614239.390817] hid-generic 0003:046D:C260.0069: input,hiddev96,hidraw0: USB HID v1.10 Joystick [Fanatec] on usb-3f980000.usb-1.1.2/input0

-vs-
Bus 001 Device 115: ID 0eb7:0e04 Endor AG
-or-
Bus 001 Device 116: ID 0eb7:0005 Endor AG
[7615164.605847] usb 1-1.1.2: new full-speed USB device number 116 using dwc_otg
[7615164.739084] usb 1-1.1.2: New USB device found, idVendor=0eb7, idProduct=0005
[7615164.739090] usb 1-1.1.2: New USB device strings: Mfr=1, Product=9, SerialNumber=0
[7615164.739094] usb 1-1.1.2: Product: FANATEC CSL Elite Wheel Base PlayStation 4
[7615164.739098] usb 1-1.1.2: Manufacturer: Fanatec
[7615164.743916] input: Fanatec FANATEC CSL Elite Wheel Base PlayStation 4 as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.1/1-1.1.2/1-1.1.2:1.0/0003:0EB7:0005.006B/input/input106
[7615164.744294] hid-generic 0003:0EB7:0005.006B: input,hiddev96,hidraw0: USB HID v1.11 Joystick [Fanatec FANATEC CSL Elite Wheel Base PlayStation 4] on usb-3f980000.usb-1.1.2/input0

however, in none of the cases the axis are working, regardless of missing or present iProduct

**Comment by lmirel** [comment]
this is the lsusb report in Linux:
Bus 001 Device 120: ID 046d:c260 Logitech, Inc.                                                                                                                                                                                                                       [350/1851]
Device Descriptor:                                          
  bLength                18              
  bDescriptorType         1                
  bcdUSB               2.00                  
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0                      
  bDeviceProtocol         0    
  bMaxPacketSize0        64                        
  idVendor           0x046d Logitech, Inc.
  idProduct          0xc260                            
  bcdDevice           89.00        
  iManufacturer           1 Fanatec
  iProduct                2 (error)
  iSerial                 0
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           41
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0
    bmAttributes         0x80
      (Bus Powered)
    MaxPower              200mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 No Subclass
      bInterfaceProtocol      0 None
      iInterface              0
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.10
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     160
         Report Descriptors:
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x03  EP 3 OUT
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               5
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x84  EP 4 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               5
Device Status:     0x0001
  Self Powered

**Comment by matlo** [comment]
046d:c260 is G29 PS4 mode. When Linux finds a G29 in PS4 mode attached, it just tries to switch the wheel to G29 PC mode. The fanatec wheel very likely does not support switching to the G29 PC mode.
