### ISSUE TITLE
How to capture mouse movement in my own app and send movements to GIMX via network?

### ISSUE THREAD

**Issue by here-to-learn** [matlo/GIMX#645]
Hi @matlo 
i want to capture the current mouse movement and send the values via network to gimx. 

to calc the mouse movement I would get the current mouse position and compare it with the old mouse position. 
which values should I then send to gimx via network? how do I know how much intensitiy I must press e.g. the right stick if my mouse movement is e.g. x = 5? How do I know I must send 32767 or 500 for example?

**Comment by matlo** [comment]
This is an issue tracker. This is not the right place for such question.

Sadly I don't have much time to learn you how to translate mouse movement to stick position. All I can say is that this task is handled by the mouse2axis2d function in core/config.c, and that the input event code is in the shared/gimxinput folder.
