### ISSUE TITLE
Add Output Bluetooth / Generic

### ISSUE THREAD

**Issue by ffiarpg** [matlo/GIMX#653]
I was hoping to use this to map keyboard and mouse on linux as a Dualshock 4 to connect to android via bluetooth. Going through the steps it seems like there are mandatory steps to mimic a DS4 and to make the emulated DS4 connect to a PS4. I assume those steps are not necessary for connecting to android so I propose an additional option to skip them.  The option to choose what controller GIMX pretends to be to android would be a bonus but not required.

**Comment by matlo** [comment]
I have currently no time for this, but I can give some directions for anyone wanting to work on this.

First thing to do is to make a hci dump on the android target while performing the bluetooth pairing. Then try to implement that in software on a Linux computer using a bluetooth dongle.

**Comment by Invictaz** [comment]
Wow, I really would have liked this as well.
