### ISSUE TITLE
GimX does not detect Titan One on latest firmware

### ISSUE THREAD

**Issue by fvig2001** [matlo/GIMX#654]
I just installed 7.15. I was able to at least connect to Titan One 2.60. I then updated to Titan One 2.66 and the device is no longer detected by Gimx. I get no GPP detected.

Device is able to work with no issues with GTuner

**Comment by matlo** [comment]
Create a file named gpp.txt in `%APPDATA%\gimx` (Windows) or `~/.gimx` (Linux), containing the following line:
```
2508 0003
```
... and let me know if it works!

**Comment by fvig2001** [comment]
It still fails. I compiled the code, which was a bigger nightmare this time (it wasn't so bad on 2013). It goes to here:
  
  switch(report.console)
  {
    case CONSOLE_DISCONNECTED:
      ret = -1;
	  	  printf("A3\n");
      break;

**Comment by fvig2001** [comment]
It seems that the old version was giving false reports when it was disconnected from the console. I ended up just connecting it to a PS3 and it seems to work even without the text file. Anyway, could you point me in the right direction to compile this to run in Windows? Msys + mingw64 gives me an exe that only works in msys and make install fails due to missing files.

**Comment by matlo** [comment]
master branch is quite ahead of version 7.15. Reinstall msys2 following the wiki instructions.
https://gimx.fr/wiki/index.php?title=Development_on_Windows
