### ISSUE TITLE
Question: Does GIMX support virtual gamepads as input?

### ISSUE THREAD

**Issue by ReenigneArcher** [matlo/GIMX#669]
A few questions.

**1. Does GIMX support virtual gamepads as input?**
My idea is to use a virtual gamepad from an Nvidia Game Stream / Moonlight session on an Android TV. Then pass that input to a game console.
_Android TV --> PC --> Console_

**2. Are multiple GIMX adapters supported on One PC?**
For multiplayer?

**Comment by matlo** [comment]
All devices that appear in the joy.cpl utility (assuming Windows for the operating system) should work.

It depends on the gaming console. There is a known bug for the PS3 (#501).
