### ISSUE TITLE
running gimx error: log name already used: GLOG_NAME

### ISSUE THREAD

**Issue by Lucashsmello** [matlo/GIMX#675]
Hi, i am trying to compile version v8.0 or the latest one on the master branch for armv7l architecture. I was able to compile and run version v7.15 successfully for this arch.
I actually compile version v8.0 (and the lastest commit on master) without any problem, but when i run gimx:
```bash
src/glog.c:45 log name already used: GLOG_NAME
```

I made a print on shared/gimxlog/src/glog.c of what names are being registered using glog and this is the result:
```
gimxuhid
gimxudp
GLOG_NAME
gimxtimer
gimxserial
gimxprio
gimxpoll
gimxhid
gimxinput
gimxfile
GLOG_NAME
```
It seems that two modules are not properly being registered on this glog (gimxusb and gimxtime, i guess?). I will continue to investigate this tomorrow.

**Comment by matlo** [comment]
Hi, this issue is due to the last commit, and the fact that the log name was not correctly set for the gimxgpp library. I just fixed it. Thanks for reporting!
