### ISSUE TITLE
macOS Support 

### ISSUE THREAD

**Issue by L1cardo** [matlo/GIMX#678]
Is it possible to have a macOS version ?

**Comment by matlo** [comment]
I am not a macOS user, nor I have any knowledge about programming on macOS. I did some preliminary work listing what is currently missing here: https://gimx.fr/wiki/index.php?title=Gasync#Porting_to_Darwin_.2F_MAC_OS_X

The possibility to someday have a macOS version entirely depends on someone else to do the port.
