### ISSUE TITLE
Default spring off

### ISSUE THREAD

**Issue by Alexanderlee1993** [matlo/GIMX#685]
![3585BB92-F16C-4090-8E1F-0832BCA9BFA3](https://user-images.githubusercontent.com/87406551/125815673-f24bc268-59eb-48b5-888f-5ee581b70eeb.png)
After about 20min it's turn off

**Comment by matlo** [comment]
Usually games turn default spring off right before starting the race, and turn it on after finishing the race. It is kind of useless.
