### ISSUE TITLE
Build falled

### ISSUE THREAD

**Issue by Filin3** [matlo/GIMX#686]
I am sorry if I do something wrong, I am a beginner in build from source.
software:
OS: Arch
gcc 11.1.0
g++ 11.1.0

commands:
git clone https://github.com/matlo/GIMX.git
git submodule init
git submodule update 
make

make output:

make[2]: Entering directory '/home/*/Downloads/GIMX/shared/gimxgpp'
cc -fPIC -Iinclude -Wall -Wextra -Werror -O3 -I../ -DGLOG_NAME=gimxgpp  -c -o pcprog.o pcprog.c
pcprog.c:387:40: error: argument 2 of type ‘int8_t[30]’ {aka ‘signed char[30]’} with mismatched bound [-Werror=array-parameter=]
  387 | int8_t gpppcprog_output(int id, int8_t output[GCAPI_INPUT_TOTAL])
      |                                 ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from pcprog.c:1:
pcprog.h:280:40: note: previously declared as ‘int8_t[36]’ {aka ‘signed char[36]’}
  280 | int8_t gpppcprog_output(int id, int8_t output[GCAPI_OUTPUT_TOTAL]);
      |                                 ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [<builtin>: pcprog.o] Error 1
make[2]: Leaving directory '/home/*/Downloads/GIMX/shared/gimxgpp'
make[1]: *** [Makefile:35: build-gimxgpp] Error 2
make[1]: Leaving directory '/home/*/Downloads/GIMX/shared'
make: *** [Makefile:15: build-shared] Error 2

**Comment by matlo** [comment]
This should be fixed on master branch.
